[2025-10-11T16:08:39.151+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T16:08:39.230+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_planes.truncate_table_planes manual__2025-10-11T16:08:31.971167+00:00 [queued]>
[2025-10-11T16:08:39.259+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_planes.truncate_table_planes manual__2025-10-11T16:08:31.971167+00:00 [queued]>
[2025-10-11T16:08:39.260+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T16:08:39.284+0000] {taskinstance.py:2327} INFO - Executing <Task(MariaDBOperator): group_planes.truncate_table_planes> on 2025-10-11 16:08:31.971167+00:00
[2025-10-11T16:08:39.294+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T16:08:39.297+0000] {standard_task_runner.py:63} INFO - Started process 228 to run task
[2025-10-11T16:08:39.297+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_planes.truncate_table_planes', 'manual__2025-10-11T16:08:31.971167+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpdklk1v_c']
[2025-10-11T16:08:39.301+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask group_planes.truncate_table_planes
[2025-10-11T16:08:39.377+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_planes.truncate_table_planes manual__2025-10-11T16:08:31.971167+00:00 [running]> on host 74db4dd39b04
[2025-10-11T16:08:39.522+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_planes.truncate_table_planes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T16:08:31.971167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T16:08:31.971167+00:00'
[2025-10-11T16:08:39.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T16:08:39.526+0000] {sql.py:276} INFO - Executing: 
                Truncate table open_flights_data.planes
                
[2025-10-11T16:08:39.541+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-11T16:08:39.553+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-11T16:08:39.554+0000] {mariadb_hook.py:37} INFO - Connecting to MariaDB database: 
[2025-10-11T16:08:39.558+0000] {sql.py:457} INFO - Running statement: 
                Truncate table open_flights_data.planes
                , parameters: None
[2025-10-11T16:08:39.561+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T16:08:39.562+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/cursors.py", line 351, in execute
    self._readresponse()
mariadb.ProgrammingError: Table 'open_flights_data.planes' doesn't exist
[2025-10-11T16:08:39.578+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_planes.truncate_table_planes, execution_date=20251011T160831, start_date=20251011T160839, end_date=20251011T160839
[2025-10-11T16:08:39.600+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task group_planes.truncate_table_planes (Table 'open_flights_data.planes' doesn't exist; 228)
[2025-10-11T16:08:39.646+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T16:08:39.661+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MariaDBOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-10-11T16:08:39.687+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T16:08:39.693+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
